name: CD - Ventas (APK)

on:
  pull_request:
    branches: [main]
    paths:
      - 'ventas/**'
  push:
    branches: [ test/ci-cd ]

jobs:
  build_apk_preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ventas

    steps:
      # 1) Descargar el código del repositorio
      - name: Download code
        uses: actions/checkout@v3

      # 2) Configurar Node.js (versión estable para React Native)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'npm'
          cache-dependency-path: ventas/package-lock.json

      #3) Instalar dependencias
      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Expo login
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build APK (preview)
        id: build
        run: |
          OUT=$(eas build --platform android --profile preview --non-interactive --json)
          echo "$OUT"
          ID=$(echo "$OUT" | node -e "const d=JSON.parse(fs.readFileSync(0,'utf8')); console.log(d[0].id)")
          echo "build_id=$ID" >> $GITHUB_OUTPUT

      - name: Download APK
        run: eas build:download --buildId ${{ steps.build.outputs.build_id }} --path app-preview.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-preview.apk
          path: ventas/app-preview.apk
